### ISSUE TITLE
Beégetések kiszervezése

### ISSUE THREAD

**Issue by sanyisasha** [tolacika/contributions-text#2]
Nem tudom JS-ben mennyire divat, de kiszervezhetnéd konstansokba/változókba azokat az értékeket, melyek bele vannak égetve.
Például:
``` javascript
return getPixelRaw(x, y) === '1' ? "█" : " ";
//...
.replace(/1/g, '░')
//...
 this.fillChar = opts.fillChar || '█';
````
Valami ilyesmi:
``` javascript
const CHAR_VALAMI = '█';
const CHAR_EMPTY = ' ';
// ...
return getPixelRaw(x, y) === '1' ? CHAR_VALAMI : CHAR_EMPTY;
```
Persze ha nem divat JS-ben akkor tárgytalan.
### Miért?
Az indok egyszerű: refactor.
Mivel nem egy fix verzióról van szó (tekintve hogy nem saját hosztolású github-ról van szó), így később változhatnak ezek a karakterek. Ha ez megtörténik, lehet keresgélni hol van még használva és mit mire is kell cserélni, mit cseréltél már...stb.

@tolacika

**Comment by tolacika** [comment]
Igazából a konstansok létjogosultságában JS-ben annyira nem hiszek, viszont ezzel adtál egy ötletet...

Mégpedig, hogy a CharMap.js-ben harmadik, opcionális paraméterként át lehessen adni a karakterkészletet, hogy mely karakterekből dolgozzon.

Illetve ahogy eddig láttam, konstansok helyett, inkább a default paraméterezést szokás használni, mint amit felhoztál példát:
```javascript
this.fillChar = opts.fillChar || '█';
```
